// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigPath() {
  return window['go']['gui']['App']['GetConfigPath']();
}

export function GetVersion() {
  return window['go']['gui']['App']['GetVersion']();
}

export function SetConfigPath() {
  return window['go']['gui']['App']['SetConfigPath']();
}

export function Start(arg1) {
  return window['go']['gui']['App']['Start'](arg1);
}

export function Test(arg1, arg2) {
  return window['go']['gui']['App']['Test'](arg1, arg2);
}
