// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engin} from '../models';

export function GetConfigPath():Promise<string>;

export function GetVersion():Promise<string>;

export function SetConfigPath():Promise<string>;

export function Start(arg1:string):Promise<boolean>;

export function Test(arg1:engin.ProgressMsg,arg2:engin.ProgressResult):Promise<void>;
